server.port=8084
spring.application.name=agrifleet-decision-service

agrifleet.db.path=agrifleet.db

spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:${agrifleet.db.path}

spring.sql.init.mode=never

logging.level.com.agrifleet=DEBUG
logging.level.org.springframework.jdbc.core=DEBUG